### ISSUE TITLE
cannot set transparency/opacity from picom 

### ISSUE THREAD

**Issue by sivaplaysmC** [FT-Labs/picom#16]
cannot set transparency/opacity from picom

**Comment by oh-wind** [comment]
I am using this fork, I think you can solve this problem by adding/modifying the following configuration.
```
mark-ovredir-focused = false
```

**Comment by FT-Labs** [comment]
Handling opacity works for me too, but use client based transparency if you don't want text to be transparent. 

mark-ovredir is correct, thanks!
